swagger: '2.0'
info:
  description: This is the backend API
  version: 1.0.0
  title: Rapids Cemetery API
  # put the contact info for your development or API team
  contact:
    email: dje2402@rit.com

  license:
    name: Apache 2.0
    url: http://team-hongkong.ist.rit.edu

# tags are used for organizing operations
tags:
- name: Front-End REST API
  description: GET data from database
- name: Admin Interface
  description: GET, POST data from/to database

########################################################
paths:
  ###################      
  /poi/getPointOfInterest.php:
    get:
      tags:
      - Front-End REST API
      summary: Returns All Points of Interest
      operationId: getPointOfInterest
      description: |
        By calling this php script it will return JSON json 
        encoded Points of Interest.
      responses:
        200:
          description: JSON Results
          schema:
            type: array
            items:
              $ref: '#/definitions/PointOfInterest'
        400:
          description: No Point of Interest Coords found.
          
  ###################      
  /poi/getTags.php:
    get:
      tags:
      - Front-End REST API
      summary: Returns All Tags and referenced PoIs
      operationId: getTags
      description: |
        By calling this php script it will return JSON json 
        encoded tags for referenced PoIs.
      responses:
        200:
          description: JSON Results
          schema:
            type: array
            items:
              $ref: '#/definitions/Tag'
        404:
          description: No Tags found.    
          
  ###################      
  /poi/getPoiCoords.php:
    get:
      tags:
      - Front-End REST API
      summary: Returns All Tags and referenced PoIs
      operationId: getPoiCoords
      description: |
        By calling this php script it will return JSON json 
        encoded map coordinates for referenced PoIs.
      responses:
        200:
          description: JSON Results
          schema:
            type: array
            items:
              $ref: '#/definitions/PoiCoordinate'
        404:
          description: No Tags found.  

  ###################      
  /poi/getPoiMedia.php:
    get:
      tags:
      - Front-End REST API
      summary: Returns All Media for referenced PoIs
      operationId: getPoiMedia
      description: |
        By calling this php script it will return JSON json 
        encoded media filenames for referenced PoIs.
      responses:
        200:
          description: JSON Results
          schema:
            type: array
            items:
              $ref: '#/definitions/PoiMedia'
        404:
          description: No Tags found. 
          
  ###################      
  /poi/getTour.php:
    get:
      tags:
      - Front-End REST API
      summary: Returns All Tour Stops for referenced PoIs
      operationId: getTour
      description: |
        By calling this php script it will return JSON json 
        encoded tour stops for referenced PoIs.
      responses:
        200:
          description: JSON Results
          schema:
            type: array
            items:
              $ref: '#/definitions/Tour'
        404:
          description: No Tags found. 
          
  ###################      
  /loc/getLocationa.php:
    get:
      tags:
      - Front-End REST API
      summary: Returns All Locations
      operationId: getLocationa
      description: |
        By calling this php script it will return JSON json 
        encoded Locations
      responses:
        200:
          description: JSON Results
          schema:
            type: array
            items:
              $ref: '#/definitions/Location'
        404:
          description: No Tags found. 
          
  ###################      
  /loc/getLocCoords.php:
    get:
      tags:
      - Front-End REST API
      summary: Returns All Map Coordinates for Locations
      operationId: getLocCoords
      description: |
        By calling this php script it will return JSON json 
        encoded map coordinates for Locations
      responses:
        200:
          description: JSON Results
          schema:
            type: array
            items:
              $ref: '#/definitions/LocCoordinate'
        404:
          description: No Tags found. 
          
  ###################      
  /loc/getLocMedia.php:
    get:
      tags:
      - Front-End REST API
      summary: Returns All Media for Locations
      operationId: getLocMedia
      description: |
        By calling this php script it will return JSON json 
        encoded media filenames for Locations
      responses:
        200:
          description: JSON Results
          schema:
            type: array
            items:
              $ref: '#/definitions/LocMedia'
        404:
          description: No Tags found. 
          
  ###################      
  /timeline/getTimeline.php:
    get:
      tags:
      - Front-End REST API
      summary: Returns Timeline Objects
      operationId: getTimeline
      description: |
        By calling this php script it will return JSON json 
        encoded Timeline Objects
      responses:
        200:
          description: JSON Results
          schema:
            type: array
            items:
              $ref: '#/definitions/Timeline'
        404:
          description: No Tags found. 
          
  ###################      
  /global/getGlobal.php:
    get:
      tags:
      - Front-End REST API
      summary: Returns Global Items
      operationId: getGlobal
      description: |
        By calling this php script it will return JSON json 
        encoded Global Items
      responses:
        200:
          description: JSON Results
          schema:
            type: array
            items:
              $ref: '#/definitions/GlobalItem'
        404:
          description: No Tags found. 
          
########################################################
definitions:
  ###################
  PointOfInterest:
    type: object
    required:
    - poiID
    - poiName
    - poiDescription
    - poiLocation
    - img_url
    - visible
    properties:
      poiID:
        type: integer
        format: AI
        example: 1
      poiName: 
        type: string
        example: Bartlett, Eliot
      poiDescription:
        type: string
        example: Born 1759; died 1851 ; age 87
      poiLocation:
        type: string
        example: Rapids Cemetery Plot J - 7
      img_url:
        type: string
        format: URL
        example: IMG_20170805_105900.jpeg
      visible:
        type: integer
        format: boolean
        example: 1

        
  ###################
  Tag:
    type: object
    required:
    - tag_id
    - poiID
    - tag_name
    properties:
      tag_id:
        type: integer
        format: AI
        example: 1
      poiID:
        type: integer
        example: 3
      tag_name:
        type: string
        example: Civil War
        
  ###################
  PoiCoordinate:
    type: object
    required:
    - point_id
    - order
    - lat
    - long
    - poiID
    properties:
      point_id:
        type: integer
        format: AI
        example: 1
      order:
        type: integer
        example: 1
      lat:
        type: number
        example: 45.76
      long:
        type: number
        example: 23.67
      poiID:
        type: integer
        example: 3
        
  ###################
  PoiMedia:
    type: object
    required:
    - point_id
    - order
    - lat
    - long
    - poiID
    properties:
      media_id:
        type: integer
        format: AI
        example: 1
      poiID:
        type: integer
        example: 3
      filename:
        type: string
        example: ../media/image1.png
      type:
        type: string
        example: image
        
  ###################
  Tour:
    type: object
    required:
    - poiID
    - tour_order
    - tour_id
    properties:
      poiID:
        type: integer
        example: 3
      tour_order:
        type: integer
        example: 1
      tour_id:
        type: integer
        format: AI
        example: 1
        
  ###################
  Location:
    type: object
    required:
    - hlID
    - hl_name
    - hl_desc
    - hl_url
    - is_trail
    properties:
      hlID:
        type: integer
        format: AI
        example: 3
      hl_name:
        type: string
        example: Susan B. Anthony House
      hl_desc:
        type: string
        example: Susan B. Anthony House, in Rochester, New York, was the home of Susan B. Anthony for forty years, while she was a national figure in the women's rights movement. She was arrested in the front parlor after attempting to vote in the 1872 Presidential Election. She resided here until her death.
      hl_url:
        type: string
        example: http://susanbanthonyhouse.org/index.php
      is_trail:
        type: boolean
        example: 0

  ###################
  LocCoordinate:
    type: object
    required:
    - loc_point_id
    - order
    - lat
    - long
    - hlID
    properties:
      loc_point_id:
        type: integer
        format: AI
        example: 1
      order:
        type: integer
        example: 1
      lat:
        type: number
        example: 87.6
      long:
        type: number
        example: 17.0
      hlID:
        type: integer
        example: 1
        
  ###################
  LocMedia:
    type: object
    required:
    - media_id
    - hlID
    - filename
    - type
    properties:
      media_id:
        type: integer
        format: AI
        example: 1
      hlID:
        type: integer
        example: 1
      filename:
        type: string
        example: ../media/sue.jpg
      type:
        type: string
        example: image
        
  ###################
  Timeline:
    type: object
    required:
    - timeID
    - point_name
    - point_year
    - point_tooltip
    properties:
      timeID:
        type: integer
        format: AI
        example: 2
      point_name:
        type: string
        example: Susan B. Anthony
      point_year:
        type: integer
        example: 1906
      point_tooltip:
        type: string
        example: "Susan B. Anthony Died: March 13, 1906, Rochester, NY"

  ###################
  GlobalItem:
    type: object
    required:
    - global_id
    - name
    - data
    properties:
      global_id:
        type: integer
        format: AI
        example: 1
      name:
        type: string
        example: data
      data:
        type: string
        example: 101203987fh1987fh12093f8h1028937fb10874fb47cny01784ync01874cn0

########################################################
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /team-hongkong-rit/Rapids-Cemetery-REST/1.0.0
schemes:
 - https