$fix_php = <<SCRIPT
#!/usr/bin/env bash

echo "output_buffering=On" > /home/vagrant/php-output-buffering.ini
docker cp /home/vagrant/php-output-buffering.ini php:"/usr/local/etc/php/conf.d/"
rm /home/vagrant/php-output-buffering.ini
docker exec php docker-php-ext-install pdo pdo_mysql
docker restart php

SCRIPT

Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/bionic64"
	config.vm.network "private_network", ip: "192.168.33.10"
	
	config.vm.synced_folder "./sql_script", "/mnt/db", :mount_options => ["dmode=777", "fmode=666"]

	config.vm.synced_folder "./dist", "/mnt/www", :mount_options => ["dmode=777", "fmode=666"]
	config.vm.synced_folder "./admin", "/mnt/www/admin", :mount_options => ["dmode=777", "fmode=666"]
	config.vm.synced_folder "./api", "/mnt/www/api", :mount_options => ["dmode=777", "fmode=666"]
	config.vm.synced_folder "./media", "/mnt/www/media", :mount_options => ["dmode=777", "fmode=666"]

	config.vm.provision "file", source: "./api/config/database-dev.php", destination: "/home/vagrant/config/database.php"

	config.vm.provision "docker" do |d|
		d.pull_images "mysql:8"
		d.pull_images "phpmyadmin/phpmyadmin"
		d.pull_images "php:7.2-apache"

		d.run "mysql",
			image: "mysql:8",
			args: "-e MYSQL_ROOT_PASSWORD=root -v '/mnt/db:/docker-entrypoint-initdb.d'",
			cmd: "--default-authentication-plugin=mysql_native_password"

		d.run "phpmyadmin",
			image: "phpmyadmin/phpmyadmin",
			args: "--link mysql:db -p 8080:80"

		d.run "php",
			image: "php:7.2-apache",
			args: "--link mysql:mysql -v '/mnt/www:/var/www/html' -v '/home/vagrant/config:/var/www' -p 80:80"
	end

	config.vm.provision "shell",
		inline: $fix_php
end